// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_service.proto

/*
Package sample_proto is a generated protocol buffer package.

It is generated from these files:
	user_service.proto

It has these top-level messages:
	GetUserRequest
	GetUserResponse
*/
package sample_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetUserRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetUserRequest) Reset()                    { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()               {}
func (*GetUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetUserRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetUserResponse struct {
	Id   int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Age  int32  `protobuf:"varint,3,opt,name=age" json:"age,omitempty"`
}

func (m *GetUserResponse) Reset()                    { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string            { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()               {}
func (*GetUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetUserResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetUserResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetUserResponse) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func init() {
	proto.RegisterType((*GetUserRequest)(nil), "sample_proto.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "sample_proto.GetUserResponse")
}

func init() { proto.RegisterFile("user_service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x2d, 0x4e, 0x2d,
	0x8a, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2,
	0x29, 0x4e, 0xcc, 0x2d, 0xc8, 0x49, 0x8d, 0x07, 0xf3, 0x94, 0x14, 0xb8, 0xf8, 0xdc, 0x53, 0x4b,
	0x42, 0x8b, 0x53, 0x8b, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0xf8, 0xb8, 0x98, 0x32,
	0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x98, 0x83, 0x98, 0x32, 0x53, 0x94, 0xdc, 0xb9, 0xf8, 0xe1,
	0x2a, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0xd1, 0x95, 0x08, 0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6,
	0xa6, 0x4a, 0x30, 0x29, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x42, 0x02, 0x5c, 0xcc, 0x89, 0xe9,
	0xa9, 0x12, 0xcc, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x20, 0xa6, 0x51, 0x28, 0x17, 0x37, 0xc8, 0x94,
	0x60, 0x88, 0x6b, 0x84, 0xdc, 0xb8, 0xd8, 0xa1, 0xe6, 0x0a, 0xc9, 0xe8, 0x21, 0xbb, 0x49, 0x0f,
	0xd5, 0x41, 0x52, 0xb2, 0x38, 0x64, 0x21, 0x8e, 0x71, 0xe2, 0x8b, 0x42, 0xf1, 0x51, 0x12, 0x1b,
	0x98, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x52, 0xb8, 0x8e, 0xf1, 0xfc, 0x00, 0x00, 0x00,
}
